/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.config;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import main.login;

/**
 *
 * @author Administrator
 */
public class Edituser extends javax.swing.JFrame {
    
    // I-declare ang userId dire para ma-access sa tibuok frame
    public int userId; 

    public Edituser() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rolecombobox = new javax.swing.JComboBox<>();
        emailfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        updateUser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update User");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 517, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 80));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Role");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        rolecombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rolecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Role", "User", "Admin", " " }));
        rolecombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        rolecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(rolecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 190, 30));

        emailfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        emailfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        updateUser.setBackground(new java.awt.Color(46, 134, 222));
        updateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateUser.setText("Update");
        updateUser.setBorder(null);
        updateUser.setPreferredSize(new java.awt.Dimension(350, 40));
        updateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserActionPerformed(evt);
            }
        });
        jPanel1.add(updateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 170, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));
        jPanel1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 210, 30));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserActionPerformed
        // Get updated user input
        String email = emailfield.getText().trim();
        String role = (String) rolecombobox.getSelectedItem();

        // Basic validation
        if ( email.isEmpty() || role.equals("Select Role")) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields and select a role.");
            return;
        }

        // Email format validation (simple regex)
        if (!email.matches("^[\\w.-]+@[\\w.-]+\\.\\w+$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
            return;
        }

        try {
            // Assume userId is available from the selected user to edit

            // Update user in the database (excluding username and password)
            String query = "UPDATE users SET u_fname = ?, u_lname = ?, u_email = ?, u_role = ? WHERE u_id = ?";
           // Ilisdi ang error nga line niini:
            java.sql.Connection conn = config.connectDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(3, email);
            pst.setString(4, role);
            pst.setInt(5, userId);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "User updated successfully.");

            // Log the update action
            int currentUserId = config.usersession.getInstance().getId();
            admin.ActionLogger.logAction(currentUserId, "Updated user info for user ID: " + userId);

            this.dispose(); // Close the update form
        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating user: " + e.getMessage());
        }
    }//GEN-LAST:event_updateUserActionPerformed

    private void rolecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolecomboboxActionPerformed

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> rolecombobox;
    private javax.swing.JButton updateUser;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables

    public void loadUser(int id) {
    config db = new config();
    try {
        ResultSet rs = db.getData("SELECT * FROM users WHERE u_id = " + id);
        if (rs.next()) {
            // I-set ang text sa imong mga fields (usba ang names base sa imong UI)
            emailfield.setText(rs.getString("u_email"));
            userField.setText(rs.getString("u_username"));
            rolecombobox.setSelectedItem(rs.getString("u_role"));
        }
    } catch (SQLException e) {
        System.out.println("Error: " + e.getMessage());
    }
}
}
